[package]
name = "manali-lang"
version = "0.1.0"
authors = ["Eli W. Hunter <elihunter173@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
# Lazy error handling
anyhow = "1.0"

# For Literal BigInt
num = "0.4"

# Parser
lalrpop-util = "0.19"
regex = "1"
bumpalo = { version = "3.4", features = ["boxed", "collections"] }
# Repl
rustyline = "7.1"
clap = { version = "3.0.0-beta.2", features = [] }

# Compilation
cranelift = "0.72.0"
cranelift-module = "0.72.0"
cranelift-jit = "0.72.0"
